## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [17]:
import pandas as pd

file1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
file2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
file3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)
df3 = pd.read_csv(file3)

In [18]:
def normalize_columns(df):
    df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')
    return df

df1 = normalize_columns(df1)
df2 = normalize_columns(df2)
df3 = normalize_columns(df3)

In [19]:
def fix_columns(df):
    df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')
    
    df.rename(columns={
        'st': 'state',
        'custateomer': 'customer',
        'custateomer_lifetime_value': 'customer_lifetime_value'
    }, inplace=True)
    
    return df

In [20]:
df1 = fix_columns(df1)
df2 = fix_columns(df2)
df3 = fix_columns(df3)

In [21]:
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

In [23]:
if 'customer_lifetime_value' in combined_df.columns:
    combined_df['customer_lifetime_value'] = combined_df['customer_lifetime_value'].astype(str).str.replace('%','')
    combined_df['customer_lifetime_value'] = pd.to_numeric(combined_df['customer_lifetime_value'], errors='coerce')

if 'number_of_open_complaints' in combined_df.columns:
    combined_df['number_of_open_complaints'] = combined_df['number_of_open_complaints'].apply(
    lambda x: int(str(x).split('/')[1]) if pd.notnull(x) and '/' in str(x) else x
)

for col in combined_df.select_dtypes(include='number'):
    combined_df[col] = combined_df[col].fillna(combined_df[col].median())

for col in combined_df.select_dtypes(include='object'):
    combined_df[col] = combined_df[col].fillna(combined_df[col].mode()[0])

combined_df = combined_df.drop_duplicates().reset_index(drop=True)

combined_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,7.714877e+03,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,6.979536e+05,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1.288743e+06,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7.645862e+05,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5.363077e+05,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [24]:
pd.concat([df1, df2, df3], axis=0)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [25]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv'
df = pd.read_csv(url)

In [27]:
df.head(5), df.columns

(   unnamed:_0 customer       state  customer_lifetime_value response  \
 0           0  DK49336     Arizona              4809.216960       No
 1           1  KX64629  California              2228.525238       No
 2           2  LZ68649  Washington             14947.917300       No
 3           3  XL78013      Oregon             22332.439460      Yes
 4           4  QA50777      Oregon              9025.067525       No

    coverage education effective_to_date employmentstatus gender  ...  \
 0     Basic   College        2011-02-18         Employed      M  ...
 1     Basic   College        2011-01-18       Unemployed      F  ...
 2     Basic  Bachelor        2011-02-10         Employed      M  ...
 3  Extended   College        2011-01-11         Employed      M  ...
 4   Premium  Bachelor        2011-01-17    Medical Leave      F  ...

    number_of_policies     policy_type        policy  renew_offer_type  \
 0                   9  Corporate Auto  Corporate L3            Offer3
 1                   1   Personal Auto   Personal L3            Offer4
 2                   2   Personal Auto   Personal L3            Offer3
 3                   2  Corporate Auto  Corporate L3            Offer2
 4                   7   Personal Auto   Personal L2            Offer1

    sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
 0          Agent          292.800000  Four-Door Car       Medsize
 1    Call Center          744.924331  Four-Door Car       Medsize
 2    Call Center          480.000000            SUV       Medsize
 3         Branch          484.013411  Four-Door Car       Medsize
 4         Branch          707.925645  Four-Door Car       Medsize

   vehicle_type month
 0            A     2
 1            A     1
 2            A     2
 3            A     1
 4            A     1

 [5 rows x 27 columns],
 Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
        'response', 'coverage', 'education', 'effective_to_date',
        'employmentstatus', 'gender', 'income', 'location_code',
        'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
        'months_since_policy_inception', 'number_of_open_complaints',
        'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
        'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
        'vehicle_type', 'month'],
       dtype='object'))

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [32]:
pivot_revenue = df.pivot_table(index='sales_channel', values='total_claim_amount', aggfunc='sum').round(2)

In [33]:
pivot_revenue

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [38]:
pivot_average_clv = df.pivot_table(index='gender', columns='education', values='customer_lifetime_value', aggfunc='mean')

In [39]:
pivot_average_clv

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here